:website:
  :id: "https://ro.alexn.org"
  :title: "ro.alexn.org"
  :description: "Pentru Hackeri, Părinţi şi Unicorni"
  :hostname: "ro.alexn.org"
  :domain: "ro.alexn.org"
  :root_url: "https://ro.alexn.org"