:website:
  :id: "https://www.spiritbionic.ro"
  :title: "Spirit Bionic"
  :description: "Spirit Bionic"
  :hostname: "www.spiritbionic.ro"
  :domain: "spiritbionic.ro"
  :root_url: "https://www.spiritbionic.ro"